### ISSUE TITLE
total_requested not verified to be > 0 TLOS

### ISSUE THREAD

**Issue by villesundell** [telosnetwork/telos-works#5]
`total_requested` is not verified to be a positive number, and it's symbol is not verified neither.

This can cause various problems, since people should not be able to request minus amounts.

A `check()` for `> 0 TLOS` should be added. Separate symbol check is not needed, since `asset`'s overloaded operator(s) will also check the symbol, along with the amount.

Context: https://github.com/telosnetwork/telos-works/blob/08436063cc0ba1d1a60f1d81347631504fa5ef95/contracts/works/src/works.cpp#L82

**Comment by craigbranscom** [comment]
Fixed in PR #7
