### ISSUE TITLE
Milestone is considered successful with 0 yes votes if abstain votes are above quorum_thresh

### ISSUE THREAD

**Issue by villesundell** [telosnetwork/telos-works#6]
If both, `yes` and `no` votes are `0`, but `abstain` votes are above the `quorum_thresh`, the milestone is considered to be successful, and the reward is paid.

The problematic line is here: https://github.com/telosnetwork/telos-works/blob/08436063cc0ba1d1a60f1d81347631504fa5ef95/contracts/works/src/works.cpp#L777

**Comment by craigbranscom** [comment]
Fixed in PR #7
